
ingress:
  domain: metaldev.chasemoskal.com
  tls: null

microservices:
  auth:
    # image: chasemoskal/auth-server:latest
    domain: auth.metaldev.chasemoskal.com
    replicas: 1
  profile:
    # image: chasemoskal/profile-server:latest
    domain: profile.metaldev.chasemoskal.com
    replicas: 1
